### PR TITLE
Implemented remove

### PR DESCRIPTION
**Pull request by alimkoca**
I implemented remove with some modification in `println!`s.

### CODE REVIEW

**Comment by alimkoca** [comment]
Also I think we need to fork instead of branching in same repository.

**Comment by muppi090909** [comment]
I do not think that it is a major problem.

**Review by muppi090909 — CHANGES_REQUESTED** [review]
Please delete the `pkg` dir. It is already implemented in the `parser` fir

**Comment by alimkoca** [comment]
It's ok.

**Review by muppi090909 — APPROVED** [review]

**Pull request merged**
